package com.example.newestandroidframe.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.newestandroidframe.mvp.entity.NewItemBean;

import com.example.newestandroidframe.greendao.NewItemBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newItemBeanDaoConfig;

    private final NewItemBeanDao newItemBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newItemBeanDaoConfig = daoConfigMap.get(NewItemBeanDao.class).clone();
        newItemBeanDaoConfig.initIdentityScope(type);

        newItemBeanDao = new NewItemBeanDao(newItemBeanDaoConfig, this);

        registerDao(NewItemBean.class, newItemBeanDao);
    }
    
    public void clear() {
        newItemBeanDaoConfig.clearIdentityScope();
    }

    public NewItemBeanDao getNewItemBeanDao() {
        return newItemBeanDao;
    }

}
